import Footer from '@/components/layout/footer';
import Nav from '@/components/layout/nav';

export const metadata = {
  title: 'Trend Matter',
  description: 'Generated by Next.js',
};

export default function HomeLayout({children}: {children: React.ReactNode}) {
  // const headersList = headers();
  // const header_url = headersList.get('x-url') || '';
  // const url = new URL(header_url);

  return (
    <>
      <Nav />
      <main className="relative">
        {children}
        {/* <Toaster position="top-right" /> */}
      </main>
      <section className="bg-dark_dark_grey padding">
        <Footer />
      </section>
    </>
  );
}
